### ISSUE TITLE
[Typst Universe] Discipline search doesn't work

### ISSUE THREAD

**Issue by jbirnick** [typst/packages#1226]
### Description

When I click on the "Mathematics" discipline, it brings me to:

https://typst.app/universe/search/?discipline=mathematics

However, this doesn't list just packages in the mathematics discipline, but instead I think it lists simply _all_ packages.

**Comment by rwmpelstilzchen** [comment]
✅ Fixed (see https://github.com/typst/webapp-issues/issues/425).

**Comment by jbirnick** [comment]
Cool! But it still doesn't show up in the side pane, even during the search (i.e. when you are on a discipline search url):
![image](https://github.com/user-attachments/assets/ae704d5e-233a-416d-bbd6-06f3f16d5d62)

Is this intended?
